#SPDX-FileCopyrightText: 2024 Linnea Gräf <nea@nea.moe>
#
#SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Firnauhi"
SPDX-PackageSupplier = "Linnea Gräf <nea@nea.moe>"
SPDX-PackageDownloadLocation = "https://github.com/nea89o/Firnauhi"

[[annotations]]
path = ["**/*.kt", "**/*.java"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = ["src/main/resources/**/*.png", "src/main/resources/**/*.mcmeta"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = ["src/main/resources/assets/firnauhi/shaders/**/*"]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = "translations/**/*.json"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = "**/fabric.mod.json"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = ["src/main/resources/assets/firnauhi/gui/**/*.xml"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = "**/*.gradle.kts"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = ["**/META-INF/services/*"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = ["src/test/resources/testdata/**/*.snbt"]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileCopyrightText = ["Linnea Gräf <nea@nea.moe>", "Firnauhi Contributors"]

[[annotations]]
path = ["src/main/resources/legacy_data/*.json"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = ["PrismarineJS Minecraft Data"]

[[annotations]]
path = ["flake.lock"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = ["Auto Generated"]
