package moe.nea.firnauhi.util.skyblock

import moe.nea.firnauhi.util.SkyblockId

object SkyBlockItems {
	val COINS = SkyblockId("SKYBLOCK_COIN")
	val ROTTEN_FLESH = SkyblockId("ROTTEN_FLESH")
	val ENCHANTED_DIAMOND = SkyblockId("ENCHANTED_DIAMOND")
	val DIAMOND = SkyblockId("DIAMOND")
	val ANCESTRAL_SPADE = SkyblockId("ANCESTRAL_SPADE")
	val ARCHAIC_SPADE = SkyblockId("ARCHAIC_SPADE")
	val DEIFIC_SPADE = SkyblockId("DEIFIC_SPADE")
	val REFORGE_ANVIL = SkyblockId("REFORGE_ANVIL")
	val SLICE_OF_BLUEBERRY_CAKE = SkyblockId("SLICE_OF_BLUEBERRY_CAKE")
	val SLICE_OF_CHEESECAKE = SkyblockId("SLICE_OF_CHEESECAKE")
	val SLICE_OF_GREEN_VELVET_CAKE = SkyblockId("SLICE_OF_GREEN_VELVET_CAKE")
	val SLICE_OF_RED_VELVET_CAKE = SkyblockId("SLICE_OF_RED_VELVET_CAKE")
	val SLICE_OF_STRAWBERRY_SHORTCAKE = SkyblockId("SLICE_OF_STRAWBERRY_SHORTCAKE")
	val ASPECT_OF_THE_VOID = SkyblockId("ASPECT_OF_THE_VOID")
	val ASPECT_OF_THE_END = SkyblockId("ASPECT_OF_THE_END")
	val BONE_BOOMERANG = SkyblockId("BONE_BOOMERANG")
	val STARRED_BONE_BOOMERANG = SkyblockId("STARRED_BONE_BOOMERANG")
	val TRIBAL_SPEAR = SkyblockId("TRIBAL_SPEAR")
	val BLOCK_ZAPPER = SkyblockId("BLOCK_ZAPPER")
	val HUNTING_TOOLKIT = SkyblockId("HUNTING_TOOLKIT")
	val ETHERWARP_CONDUIT = SkyblockId("ETHERWARP_CONDUIT")
}
